version: '3.9'

# Docker Compose for TrueGradient (Atlas MongoDB)
# Assumes you provide a .env file in project root with the required variables below.
# MongoDB Atlas is external, so no local mongo service is defined.

services:
  backend:
    build:
      context: ./backend
    container_name: truegradient-backend
    env_file:
      - ./.env
    environment:
      # Explicitly override PORT inside container
      - PORT=5001
    ports:
      - "5001:5001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        # Pass backend URL at build time so Vite embeds it in bundle
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:5001}
    container_name: truegradient-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

# No volumes are strictly required; add bind mounts for live dev if needed.
